# culture=“en-US”
ConvertFrom-StringData @'
	AppName = Corefig 1.1
	Tools = Tools
	CommandPrompt = Command Prompt
	TaskManager = Task Manager
	RegistryEditor = Registry Editor
	SysInfo = System Information
	Logs = Logs
	ShowLogFile = Show Log File
	ClearLogFile = Clear Log File
	ComputerName = Computer Name
	WorkgroupOrDomain = Workgroup/Domain
	SKUVersion = Operating System
	Help = Help
	About = About
	CPMenuDescription = Control Panel for Windows Server 2012 Hyper-V and Core
	CPMenuTitle = Control Panel Menu
	RegionalDescription = Keyboard, time, and date settings
	DTButton = Date and Time...
	KBButton = Keyboard...
	FWButton = Firewall...
	ARPButton = Add/Remove Programs...
	DriversButton = Drivers...
	DisplayButton = Display Settings...
	WUButton = Windows Updates...
	FWDescription = Windows Firewall status and rules
	ARPDescription = Add or remove programs
	DriversDescription = Add driver files
	DisplayDescription = Change display resolution and screensaver timeout
	WUDescription = Configure Windows Updates for direct connection or WSUS
	RegionalTitle = Regional Settings
	ARPTitle = Programs
	FWTitle = Firewall Settings
	DriverTitle = Hardware Settings
	WUTitle = Windows Update Settings
	DisplaySettings = Display Settings
'@
