# culture=“en-US”
ConvertFrom-StringData @'
	AppName = Corefig 1.1
	ComputerName = Computer Name
	WorkgroupOrDomain = Workgroup/Domain
	SKUVersion = Operating System
	Tools = Tools
	CommandPrompt = Command Prompt
	TaskManager = Task Manager
	RegistryEditor = Registry Editor
	SysInfo = System Information
	Logs = Logs
	ShowLogFile = Show Log File
	ClearLogFile = Clear Log File
	LogClearedBy = Log file cleared by {0}
	Help = Help
	About = About
	LogCommandExecuted = {0} Command Executed: {1}
	BackButton = < Back
	PageTitle = Computer Settings Menu
	PageDescription = Domain membership, roles, services, and remote settings
	RDButton = Remote Desktop...
	RMDescription = Remote management and remote desktop settings
	RMTitle = Remote Management Settings
	DCPButton = DCPromo Disabled
	ServicesButton = Services...
	RolesButton = Add or Remove Roles...
	NameDomainButton = Computer Name and Domain...
	DCPDescription = This tool does not support domain controller promotion in 2012 (yet)
	ServicesDescription = Manage Windows services
	RolesDescription = Manage roles and features
	NameDomainDescription = Change the computer name and/or join or leave a domain
	ServicesTitle = Services
	DCTitle = Domain Controller Settings
	RolesTitle = Roles and Features
	NameDomainTitle = Computer Name and Domain Settings
	WinRMButton = WinRM...
'@
