# culture=“en-US”
ConvertFrom-StringData @'
	AppName = Corefig 1.0
	Tools = Tools
	CommandPrompt = Command Prompt
	TaskManager = Task Manager
	RegistryEditor = Registry Editor
	SysInfo = System Information
	Logs = Logs
	ShowLogFile = Show Log File
	ClearLogFile = Clear Log File
	ComputerName = Computer Name
	WorkgroupOrDomain = Workgroup/Domain
	SKUVersion = Operating System
	Help = Help
	About = About
	AppDescription = Tool for configuring Windows Server 2012 Core or Hyper-V
	LoadAtStartup = Load at windows startup
	LogOffDotted = Log off...
	RestartDotted = Restart...
	ShutDownDotted = Shut Down...
	Start = Start
	Exit = Exit
	TitleMain = Corefig Main Menu
	HyperVSettings = Hyper-V Settings
	NetworkSettings = Network Settings
	ControlPanel = Control Panel
	ComputerSettings = Computer Settings
	LicenseSettings = License Settings
	HyperVSettingsDotted = Hyper-V Settings...
	NetworkSettingsDotted = Network Settings...
	ControlPanelDotted = Control Panel...
	ComputerSettingsDotted = Computer Settings...
	LicenseSettingsDotted = License Settings...
	HyperVDescription = Start or stop virtual machines
	NetworkingDescription = Change network adapter and proxy settings
	ControlPanelDescription = Windows Update, display settings and Windows Firewall
	ComputerSettingsDescription = Configure computer name, domain membership, and Windows roles and features
	LicenseDescription = Current server license status,online/offline activation, and product key configuration
	AppStart = {0} {1} started by {2}
	AppExit = {0} {1} stopped by {2}
	LogClearedBy = Log file cleared by {0}
	LogCommandExecuted = {0} Command Executed: {1}
	LogoffWarning = Logoff Warning
	LogoffVerify = Click "OK" to continue server log off or "Close" to cancel
	LogoffBy = Server Logoff by {0}
	RestartWarning = Restart Warning
	RestartVerify = Click "OK" to continue server restart or "Close" to cancel
	RestartBy = Server restarted by {0}
	ShutdownWarning = Shutdown Warning
	ShutdownVerify = Click "OK" to continue server shutdown or "Close" to cancel
	ShutdownBy = Server shut down by {0}
'@