# culture=“en-US”
ConvertFrom-StringData @'
	AppName = Corefig 1.0
	PageTitle = Firewall Settings Menu
	Close = Close
	RuleConfiguration = Rule Configuration
	FirewallSettings = Firewall Settings
	Current = Current Firewall Status
	Enabled = Enabled
	Disabled = Disabled
	RemoteDesktop = Remote Desktop
	InboundRules = Inbound Rules
	RemoteScheduledTaskManagement = Remote Scheduled Task Management
	RulesDescription = These rules are representative of rule groups. When you click "Apply", all members of the group will be modified.
	PingDescription = ICMP Echo Requests (Ping)
	RemoteVolumeManagement = Remote Volume Management
	Status = Status
	ServiceManagement = Service Management
	SMBDirect = SMB Direct (iWARP)
	EventLogManagement = Event Log Management
	FileAndPrinterSharing = File and Printer Sharing Management
	WindowsFirewallRemoteManagement = Windows Firewall Remote Management
	WindowsRemoteManagement = Windows Remote Management
	PublicNetworks = Public Networks
	PrivateNetworks = Private Networks
	DomainNetworks = Domain Networks
	DomainLocations = Domain Network Locations
	PrivateLocations = Private Network Locations
	PublicLocations = Public Network Locations
	TurnOffFirewall = Turn Off Windows Firewall (Not Recommended)
	TurnOnFirewall = Turn On Windows Firewall
	Apply = Apply
	PageDescription = Windows Firewall can help prevent hackers or malicious software from gaining access to your computer through the Internet or a network.
	Domain = Domain
	Private = Private
	Public = Public
	LogCommandExecuted = {0} Command Executed: {1}
	LogProfileChanged = {0} {1} Firewall Profile {2}
	LogRuleGroupChanged = {0} Firewall rule group {1} set to {2}
'@