# culture=“en-US”
ConvertFrom-StringData @'
	PageTitle = Corefig 1.1 Networking Menu
	PageDescription = Networking, Shares, Proxy, and iSCSI Configuration
	Tools = Tools
	CommandPrompt = Command Prompt
	TaskManager = Task Manager
	RegistryEditor = Registry Editor
	SysInfo = System Information
	Logs = Logs
	ShowLogFile = Show Log File
	ClearLogFile = Clear Log File
	ComputerName = Computer Name
	WorkgroupOrDomain = Workgroup/Domain
	SKUVersion = Operating System
	Help = Help
	About = About
	MPIOConfig = MPIO Configuration...
	iSCSIConfig = iSCSI Configuration...
	ProxyConfig = Proxy Configuration...
	ShareConfig = Share Management...
	GroupConfig = Group Membership...
	NICConfig = Network Interface Cards...
	iSCSIDescription = Connect to iSCSI targets and modify multi-path I/O settings
	ProxyDescription = Modify proxy settings
	ShareDescription = Modify local group membership and network shares
	iSCSILabel = iSCSI Settings
	AdapterDescription = Manage network adapters, including IPv4 settings
	ShareLabel = Group and Share Settings
	NetworkLabel = Network Settings
	InternetSettings = Internet Settings
'@